import type { ScenarioFixture, ScenarioId } from "./types";

export const scenarioIds: readonly ScenarioId[] = [
  "S01_HAPPY_FULL_FULFILLMENT",
  "S02_DUPLICATE_COMMERCE_EVENT",
  "S03_ACK_BEFORE_ORDER",
  "S04_MISSING_SKU_HOLDS_RELEASE",
  "S05_SHORT_SHIPMENT_BACKORDER",
  "S06_SHORT_SHIPMENT_CLOSE_SHORT",
  "S07_CANCEL_BEFORE_RELEASE",
  "S08_CANCEL_AFTER_WMS_ACK",
  "S09_CANCEL_AFTER_SHIPMENT",
  "S10_CARRIER_TIMEOUT_AFTER_CREATE",
  "S11_COMMERCE_FULFILLMENT_THROTTLED",
  "S12_MISSED_UPDATE_RECONCILED",
  "S13_TRACKING_CONFLICT",
  "S14_WORKER_CRASH_RECOVERY",
  "S15_CROSS_TENANT_ATTACK",
];

export const scenarioFixtures: readonly ScenarioFixture[] = [];
